# Generated by Django 3.1.2 on 2020-12-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmlcss.restaurant'),
        ),
    ]
