# Generated by Django 3.1.2 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermore',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='customermore',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='restaurantmore',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='restaurantmore',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-picture_0_0.png', null=True, upload_to='static/images'),
        ),
    ]
