# Generated by Django 3.1.2 on 2020-12-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0002_auto_20201207_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
